# k8s/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2 # Run 2 instances for basic availability
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: web
          image: stellar_care-web:latest
          imagePullPolicy: IfNotPresent # Or IfNotPresent for local testing, 'Always' ensures updates are pulled
          ports:
            - containerPort: 8000 # Port Gunicorn listens on
          envFrom: # Load vars from ConfigMap and Secret
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret # References secret created via kubectl
          # Liveness and Readiness Probes help K8s manage your app
          # Ensure your application has a /api/health/ (or similar) endpoint that returns HTTP 200.
          readinessProbe:
            httpGet:
              path: /api/health/ # IMPORTANT: Replace with your actual health check endpoint
              port: 8000
            initialDelaySeconds: 20 # Wait 20s before first probe (allow app to start)
            periodSeconds: 20   # Probe every 20s
            timeoutSeconds: 5     # Probe timeout
            failureThreshold: 3 # Consider pod unhealthy after 3 failures
          livenessProbe:
            httpGet:
              path: /api/health/ # IMPORTANT: Replace with your actual health check endpoint
              port: 8000
            initialDelaySeconds: 45 # Wait 45s before first probe (allow more time than readiness)
            periodSeconds: 30   # Probe every 30s
            timeoutSeconds: 5     # Probe timeout
            failureThreshold: 3 # Restart pod after 3 failures