# Generated by Django 5.2.1 on 2025-05-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_patient_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='patient',
        ),
    ]
