# Generated by Django 5.2.1 on 2025-05-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_billing_options_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
