# Generated by Django 5.2.1 on 2025-05-23 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_rename_diagnosis_appointment_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='billing',
            name='date_billed',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22)),
        ),
        migrations.AddField(
            model_name='billing',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
