# Generated by Django 5.2.1 on 2025-05-23 18:25

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date_billed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 18, 25, 55, 347638, tzinfo=datetime.timezone.utc)),
        ),
    ]
