# Generated by Django 5.2.1 on 2025-05-23 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_billing_date_billed_alter_billing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 18, 28, 32, 933504, tzinfo=datetime.timezone.utc)),
        ),
    ]
