# Generated by Django 5.2.1 on 2025-05-23 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_billing_due_date_alter_doctor_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 18, 44, 48, 861270, tzinfo=datetime.timezone.utc)),
        ),
    ]
