# Generated by Django 5.2.1 on 2025-05-23 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_billing_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='license_number',
        ),
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 18, 47, 55, 843151, tzinfo=datetime.timezone.utc)),
        ),
    ]
