# Generated by Django 5.2.1 on 2025-05-23 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_remove_doctor_license_number_alter_billing_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(default='00000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 18, 57, 12, 106554, tzinfo=datetime.timezone.utc)),
        ),
    ]
