# Generated by Django 5.2.1 on 2025-05-31 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_alter_billing_due_date_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 30, 16, 56, 43, 804582, tzinfo=datetime.timezone.utc)),
        ),
    ]
