# Generated by Django 5.2.1 on 2025-05-31 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_alter_billing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 30, 17, 41, 42, 257598, tzinfo=datetime.timezone.utc)),
        ),
    ]
