# Generated by Django 5.2.1 on 2025-06-03 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_alter_billing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 3, 23, 23, 18, 406795, tzinfo=datetime.timezone.utc)),
        ),
    ]
