# Generated by Django 5.2.1 on 2025-06-04 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_alter_billing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 3, 32, 32, 12002, tzinfo=datetime.timezone.utc)),
        ),
    ]
