# Generated by Django 5.2.1 on 2025-06-04 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_alter_billing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 4, 17, 36, 491765, tzinfo=datetime.timezone.utc)),
        ),
    ]
