# Generated by Django 5.2.1 on 2025-06-05 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_alter_billing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 5, 14, 3, 35, 212848, tzinfo=datetime.timezone.utc)),
        ),
    ]
