# Generated by Django 5.2.1 on 2025-06-07 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0027_alter_billing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 7, 21, 2, 41, 277627, tzinfo=datetime.timezone.utc)),
        ),
    ]
